before_all do
  Dotenv.load ".env.secret"
end

desc "Create app in Developer Portal and on App Store Connect"
lane :create_app do
  # create_app_online #produce
  produce(
    language: 'English',
    enable_services: {
      apple_pay: "on",
      associated_domains: "on",
      push_notification: "on"
    },
    itc_users: ["fahed@saee.sa","raja.n@saee.sa"]
  )
  end

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end

  desc "Generate screenshots"
  lane :generate_screenshots do
    capture_screenshots
  end

  desc "Sync signing"
  lane :signing do
    get_push_certificate
    # generate_screenshots
    sync_code_signing #match
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    signing
    build_ios_app #gym
  end

  desc "Release binary"
  lane :release do
    build
    upload_to_app_store #deliver
  end

  lane :submit_review do
    deliver(
      build_number: '1',
      submit_for_review: false,
      automatic_release: true,
      force: true,
      skip_metadata: false,
      skip_screenshots: true,
      skip_binary_upload: true,
      submission_information: {
        export_compliance_uses_encryption: false,
        add_id_info_uses_idfa: false
      },
      app_rating_config_path: 'fastlane/metadata/app_store_rating_config.json',
      price_tier: 0
    )
  end

  lane :distribute do
    upload_to_testflight(
      app_identifier: ENV['MATCH_APP_IDENTIFIER'],
      demo_account_required: false,
      build_number: '1',
      groups:[
        "Pak Office",
        "Jeddah Office"
      ],
      # ipa: ENV['GYM_OUTPUT_DIRECTORY'] + '/' + ENV['PRODUCE_APP_NAME'] + '.ipa',
      localized_app_info: {
        "default": {
          feedback_email: ENV['DISTRIBUTE_FEEDBACK_EMAIL'],
          marketing_url: ENV['DISTRIBUTE_MARKETING_URL'],
          privacy_policy_url: ENV['DISTRIBUTE_PRIVACY_POLICY_URL'],
          description: "This is a description of my app",
        },
        "en-US": {
          feedback_email: ENV['DISTRIBUTE_FEEDBACK_EMAIL'],
          marketing_url: ENV['DISTRIBUTE_MARKETING_URL'],
          privacy_policy_url: ENV['DISTRIBUTE_PRIVACY_POLICY_URL'],
          description: "This is a description of my app",
        }
      },
      notify_external_testers: true,
      distribute_external: true,
      # skip_waiting_for_build_processing: true,
      distribute_only: true,
      changelog: "This is my changelog of things that have changed in a log",
      beta_app_review_info: {
        contact_email: ENV['DISTRIBUTE_FEEDBACK_EMAIL'],
        contact_first_name: "Fahed",
        contact_last_name: "Yasin",
        contact_phone: "+923334705906",
        demo_account_name: "",
        demo_account_password: "",
        notes: "this is review note for the reviewer <3 thank you for reviewing"
      }
    )
  end
end