before_all do
  Dotenv.load ".env.secret"
end

desc "Create app in Developer Portal and on App Store Connect"
lane :create_app do
  # create_app_online #produce
  produce(
    enable_services: {
      apple_pay: "on",
      associated_domains: "on",
      push_notification: "on"
    }
  )
  end

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end

  desc "Generate screenshots"
  lane :generate_screenshots do
    capture_screenshots
  end

  desc "Sync signing"
  lane :signing do
    # generate_screenshots
    sync_code_signing #match
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    signing
    build_ios_app #gym
  end

  desc "Release binary"
  lane :release do
    build
    upload_to_app_store #deliver
  end
end

platform :mac do
end